feat: endContent prop added to AccordionItem component
nextui-org/nextui pull request #1340
Opened 2023-08-10 01:08 UTC by Jlassiezzeddine

📝 Description
As requested in #1295 (feature request), endContent prop is added to the AccordionItem component

⛳️ Current behavior (updates)
We can just pass startContent prop which usually renders an icon or avatar

🚀 New behavior
We can now pass endContent prop which can render an icon, an avatar or a button (that's what's generally needed)

💣 Is this a breaking change (Yes/No):
No

📝 Additional Information
I added the Button component to the package as dev dependecy, updated the theme and created the stories for Accordion "With End Content" and "With Start And End Content"

2023-08-10 04:28 UTC, jguddas requested changes
I got some bad news, interactive elements can't be nested, no `button` inside `button`.

![Screenshot of storybook accessibility panel showing the following error](https://github.com/nextui-org/nextui/assets/25524993/c87f02fb-3111-4f74-a8e6-dc87d285ae65)

https://dequeuniversity.com/rules/axe/4.7/nested-interactive

2023-08-10 05:08 UTC, jguddas commented
The way to solve this is IMO a redundant click handler on the h2 and a hidden button for a11y.

```tsx
import { usePress, VisuallyHidden } from "react-aria";

export default function Example({ onPress }) {
  let { pressProps: redundentPressProps } = usePress({ onPress });
  let { pressProps: buttonPressProps } = usePress({ onPress });
  return (
    <h2 {...redundentPressProps}>
      Hello World!
      <VisuallyHidden>
        <button {...buttonPressProps}>toggle</button>
      </VisuallyHidden>
    </h2>
  );
}
```

2023-08-10 23:29 UTC, Jlassiezzeddine commented
@jguddas  I can't find out how to do it the way your mentionned, I think it's impossible to do nesting interactive elements anyway.

I found a way to put the actions outside of the accordion item button (which is the trigger), but keep it inside the H2 (the header) and position it absolutely in the middle of the heading

![accordion](https://github.com/nextui-org/nextui/assets/46867906/5124dcd0-3d4e-40fb-b94d-1ed32b794ea2)

It's accessible and working well.

What do you think ?

2023-08-11 07:02 UTC, jguddas commented
> What do you think ?

It's super flaky, put a Lorem Ipsum in there and you will see:

1. It looks funky
2. If you have non-interactive elements in there, the click does not get propagated.

I can take a look on the weekend and see if I can get my suggestion pushed.

2023-08-15 23:50 UTC, mauriciabad commented on packages/core/theme/src/components/accordion.ts
> +      "flex py-4 w-full h-full gap-3 outline-none items-center tap-highlight-transparent ",
```suggestion
      "flex py-4 w-full h-full gap-3 outline-none items-center tap-highlight-transparent",
```

Unnecessary white space.

2023-10-01 15:20 UTC, closed without merging