fix: #1648
nextui-org/nextui pull request #1655
Opened 2023-09-19 03:30 UTC by anshmourya

fix: #1648

2023-09-22 13:55 UTC, jrgarciadev requested changes

2023-09-22 13:55 UTC, jrgarciadev commented on .changeset/dry-teachers-doubt.md
> +---
@anshmourya could you please add a changeset with description?

run `changeset` select the navbar package and add the description

Fix #NUMBER_OF_ISSUE, explanation..

Push the new changeset

Thank you!

2023-09-23 05:04 UTC, anshmourya commented
@jrgarciadev please review the chnages.

2023-09-23 12:36 UTC, jrgarciadev approved these changes
Thank you! 🙏🏻 @anshmourya

2023-09-23 12:36 UTC, merged