fix(components): accordion component throws "validateDOMNesting" erro…
nextui-org/nextui pull request #2169
Opened 2023-12-26 01:46 UTC by kuri-sun

Closes #2168

## 📝 Description

The accordion component throws a "validateDOMNesting" error on the storybook

## ⛳️ Current behavior (updates)

When you open up the Accordion component(Custom with classNames) on the storyboard, you will get an error console message that says "validateDOMNesting(...) cannot appear as a descendant of p".(the pic below)
![error](https://github.com/nextui-org/nextui/assets/62743644/8daa27bc-172f-48a0-9604-3969966f8929)

## 🚀 New behavior

There are no errors in the console.

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information

2024-02-08 13:31 UTC, jrgarciadev requested changes

2024-02-08 13:31 UTC, jrgarciadev commented on .changeset/silver-walls-drum.md
> +---
@kuri-sun please remove this file, it is not needed for storybook's changes.

2024-02-08 18:35 UTC, jrgarciadev commented
@kuri-sun sorry, could you please modify this component code as well? https://nextui.org/docs/components/accordion#start-content

2024-02-08 22:09 UTC, kuri-sun commented
@jrgarciadev Absolutely

2024-02-13 02:23 UTC, kuri-sun commented
@jrgarciadev The requested change was modified. Thank you! 😄

2024-03-03 21:32 UTC, jrgarciadev commented
@kuri-sun could you please update this as well?  https://vscode.dev/github/nextui-org/nextui/blob/main/apps/docs/content/components/accordion/custom-styles.ts#L217

2024-03-03 22:36 UTC, kuri-sun commented
@junior Of course, immediately!

2024-03-03 23:36 UTC, jrgarciadev approved these changes

2024-03-03 23:36 UTC, merged