fix(input): resolve RTL support (#2315)
nextui-org/nextui pull request #2316
Opened 2024-02-05 18:19 UTC by mrbadri

Closes # 2315

## 📝 Description

Add RTL support to the input component.

## ⛳️ Current behavior (updates)

The input component currently lacks support for right-to-left (RTL) direction.

## 🚀 New behavior

This PR addresses the RTL support issue in the input component, ensuring correct rendering in RTL environments.

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

- Resolves issue #2315
- Added RTL support to the input component

2024-02-13 00:36 UTC, jrgarciadev commented
@mrbadri it worked fine, thank you!, could you please add the changeset?

2024-02-18 20:37 UTC, mrbadri commented
Hi [jrgarciadev](https://github.com/jrgarciadev),  thank you for review my pull request

when i run 'pnpm changeset'
i get this error : 
🦋  Which packages would you like to include? · No items were selected
🦋  error You must select at least one package to release
🦋  error (You most likely hit enter instead of space!)

i can't add changeset

2024-02-21 09:58 UTC, mrbadri commented
Hi [jrgarciadev](https://github.com/jrgarciadev),
I add changeset

2024-03-03 21:23 UTC, jrgarciadev requested changes

2024-03-03 21:23 UTC, jrgarciadev commented on .changeset/curly-pandas-guess.md
> +"@nextui-org/input": major
@mrbadri 

```suggestion
"@nextui-org/input": patch
```

Update the changeset to be a `patch`, when creating it just press enter without selecting that it is a `major` / `minor`

2024-03-04 08:11 UTC, itmysm commented
Hi Mohammad Reza! if you need any help with RTL support, I'm ready to help you.

2024-03-08 09:44 UTC, mrbadri commented
Hi [jrgarciadev](https://github.com/jrgarciadev),

I hope you're doing well! I've made some updates to address the feedback you provided earlier. Could you please take another look at my pull request when you have a moment? Your feedback is greatly appreciated.

Thank you!

Mohammad Reza Badri

2024-03-16 01:51 UTC, jrgarciadev approved these changes
Thank you! @mrbadri

2024-03-16 01:52 UTC, merged