fix(components): autocomplete, tabIndex is not passed on input
nextui-org/nextui pull request #2375
Opened 2024-02-18 09:01 UTC by kuri-sun

Closes #2372

## 📝 Description

Autocomplete, tabIndex is not passed on input

## ⛳️ Current behavior (updates)

`inputProps` don't get passed down to the input element.

## 🚀 New behavior

It is used to `otherProps` override `slotsProps.inputProps`. Now `slotsProps.inputProps`(user input) takes precedence over.

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information

2024-02-18 13:12 UTC, jrgarciadev commented
Good catch! @kuri-sun could you please add the changeset?

2024-02-18 16:13 UTC, kuri-sun commented
@jrgarciadev Absolutely

2024-03-03 21:10 UTC, jrgarciadev requested changes

2024-03-03 21:10 UTC, jrgarciadev commented on .changeset/metal-gorillas-dress.md
> +"@nextui-org/autocomplete": major
```suggestion
"@nextui-org/autocomplete": patch
```

@kuri-sun please update the changeset to be a patch

2024-03-03 23:37 UTC, jrgarciadev approved these changes

2024-03-03 23:37 UTC, merged