Fix/eng 429
nextui-org/nextui pull request #2444
Opened 2024-03-04 23:25 UTC by alphaxek

Closes https://github.com/nextui-org/nextui/issues/2420

## 📝 Description

- revised the isReadOnly logic in Autocomplete
- created isReadOnly example in storybook

## ⛳️ Current behavior (updates)
when isReadOnly is set, users

- cannot edit the input
- can open the listbox
- can select the menu option

## 🚀 New behavior
when isReadOnly is set, users

- cannot edit the input
- can open the listbox
- cannot select the menu option

## 💣 Is this a breaking change (Yes/No):
No

## 📝 Additional Information
When someone prefer to not open the listbox, then they should use isDisabled instead.

2024-03-05 02:24 UTC, wingkwong requested changes
I've made the [PR](https://github.com/nextui-org/nextui/pull/2429) 3 days ago. You don't need to copy my changes and add your own. You can simply supplement the doc part in this PR. In this case, a changeset is not required.

2024-03-05 19:17 UTC, jrgarciadev requested changes
Hey @alphaxek please update this PR with the latest `main` changes

2024-03-05 19:17 UTC, jrgarciadev commented on apps/docs/content/docs/components/autocomplete.mdx
> +If you pass the `isReadOnly` property to the autocomplete, the listbox will open to display
```suggestion
If you pass the `isReadOnly` property to the Autocomplete, the Listbox will open to display 
```

2024-03-05 22:10 UTC, alphaxek commented
> I've made the [PR](https://github.com/nextui-org/nextui/pull/2429) 3 days ago. You don't need to copy my changes and add your own. You can simply supplement the doc part in this PR. In this case, a changeset is not required.

Hi @wingkwong , I apologize I actually was trying to add my changes to your PR, but since it was my first time doing dual PR, I kind of messed it up, I didn't think it was going to create a whole new PR, I didn't intent to, if you want I can take it back, let me know, thanks

2024-04-15 14:36 UTC, jrgarciadev approved these changes
Thanks! @alphaxek

2024-04-15 14:36 UTC, merged