chore/added eslint import no duplicates
nextui-org/nextui pull request #929
Opened 2022-12-01 16:53 UTC by jguddas

- chore: added eslint import/no-duplicates
- chore: unified duplicate import

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-12-01 16:55 UTC, jguddas commented
@gauravkrp what do you think?

2022-12-01 18:05 UTC, gauravkrp approved these changes
@jguddas looks good!

2023-01-04 02:49 UTC, tianenpang requested changes

2023-01-04 02:49 UTC, tianenpang commented on packages/react/src/tooltip/tooltip.tsx
> +import {CSS} from "../theme/stitches.config";
Hey @jguddas duplicate `CSS` type imported here.

2023-01-06 02:19 UTC, tianenpang approved these changes
Hi @jrgarciadev LGTM, ready to merge. Thanks @jguddas 🚀

2023-01-07 01:29 UTC, jrgarciadev commented
Huge thanks @jguddas! 🚀

2023-01-07 01:29 UTC, merged